# src/box2d/world.py

import math
import traceback

from ._box2d import lib, ffi
from .body import BodyBuilder, Body
from .joint import (
    MouseJoint,
    WeldJoint,
    RevoluteJoint,
    PrismaticJoint,
    WheelJoint,
    DistanceJoint,
    MotorJoint,
)
from .math import Vec2, Rot, VectorLike, AABB, Transform
from .dataclasses import BodyDef, BodyType
from .events import (
    BodyMoveEvent,
    Contact,
    ContactBeginEvent,
    ContactEndEvent,
    ContactEvents,
    ContactHitEvent,
    JointEvent,
)
from .jointdef import (
    JointDef,
    WeldJointDef,
    RevoluteJointDef,
    PrismaticJointDef,
    WheelJointDef,
    DistanceJointDef,
    MotorJointDef,
    MouseJointDef,
)
from .debug_draw import DebugDraw
from .collision_filter import CollisionFilter
from .shape import Shape
from .lifetime import IdRef, DestroyedError, raw_id, is_live
from dataclasses import dataclass


@dataclass
class RayCastResult:
    """Result from a ray cast query."""

    shape: "Shape"  # Shape that was hit
    point: Vec2  # Hit point in world coords
    normal: Vec2  # Surface normal at hit point
    fraction: float  # Fraction along ray where hit occurred (0-1)


@dataclass
class SensorEvent:
    """Event generated by a sensor contact."""

    sensor: "Shape"  # Sensor shape generating the event
    visitor: "Shape"  # Other shape involved in the event
    begin: bool  # True if the sensor is starting to overlap the other shape False if ending


@dataclass
class SensorEvents:
    """Collection of sensor events generated during a time step."""

    begin: list[SensorEvent]
    end: list[SensorEvent]


def make_ray_cast_callback(results: list):
    """Create a ray cast callback function."""

    @ffi.callback("float(b2ShapeId, b2Vec2, b2Vec2, float, void*)")
    def ray_cast_callback(shape_id, point, normal, fraction, _):
        shape = ffi.from_handle(lib.b2Shape_GetUserData(shape_id))
        result = RayCastResult(
            shape=shape,
            point=Vec2(point.x, point.y),
            normal=Vec2(normal.x, normal.y),
            fraction=fraction,
        )
        results.append(result)
        return 1.0  # Continue querying

    return ray_cast_callback


def make_overlap_callback(results: list, max_results: int = None):
    """
    Create an overlap callback that appends detected shapes to the results
    list and stops querying when max_results is reached.

    Args:
        results: A list to collect overlapping shapes.
        max_results: Optional maximum number of shapes to collect. Once reached,
                     the callback returns False to stop further processing.

    Returns:
        A Box2D-compatible callback function.
    """

    @ffi.callback("bool(b2ShapeId, void*)")
    def overlap_callback(shape_id, _):
        shape = ffi.from_handle(lib.b2Shape_GetUserData(shape_id))
        results.append(shape)
        if max_results is not None and len(results) >= max_results:
            return False  # Stop querying further shapes
        return True  # Continue querying

    return overlap_callback


class World:
    """2D physics world containing bodies, joints, and simulation parameters.

    Manages Box2D world state and provides body creation through a builder pattern.
    Wraps Box2D's b2World functionality with Pythonic interfaces.

    Example:
        >>> world = World(gravity=(0, -9.81))
        >>> body = world.new_body().dynamic().position(0, 5).box(1, 1).build()
        >>> for _ in range(60):
        ...     world.step(1/60, 4)
    """

    _world_id = IdRef(lib.b2World_IsValid, "world")

    def __init__(self, gravity: VectorLike = (0, -10), threads: int = 1):
        """Initialize physics world with specified gravity vector.

        Args:
            gravity: Initial gravitational acceleration (x,y) in m/s².

        Example:
            >>> world = World(gravity=(0, -9.8))
            >>> world.gravity
            Vec2(0.0, -9.8)
        """

        world_def = lib.b2DefaultWorldDef()
        world_def.gravity.x, world_def.gravity.y = gravity
        self._threads = threads
        if threads > 1:
            # Use the C-level task scheduler
            lib.setup_threadpool(threads)
            self._use_c_scheduler = True
            world_def.workerCount = threads
            world_def.enqueueTask = lib.c_enqueue_tasks
            world_def.finishTask = lib.c_finish_tasks
            self._user_task_ctx = ffi.new_handle(self)
            world_def.userTaskContext = self._user_task_ctx
        else:
            self._use_c_scheduler = False

        self._handle = ffi.new_handle(self)
        world_def.userData = self._handle

        self._world_id = lib.b2CreateWorld(ffi.addressof(world_def))

        # Store default simulation parameters
        self._enable_sleep = world_def.enableSleep
        self._enable_continuous = world_def.enableContinuous
        self._restitution_threshold = world_def.restitutionThreshold
        self._hit_event_threshold = world_def.hitEventThreshold
        self._contact_hertz = world_def.contactHertz
        self._contact_damping_ratio = world_def.contactDampingRatio
        self._contact_push_velocity = world_def.contactSpeed

        self._bodies = {}

        # Callbacks, with the cffi trampolines that must outlive them.
        self._custom_filter = self._custom_filter_trampoline = None
        self._pre_solve = self._pre_solve_trampoline = None
        self._friction_mixer = self._friction_trampoline = None
        self._restitution_mixer = self._restitution_trampoline = None

    @property
    def gravity(self):
        """World gravity vector (m/s²).

        Example:
            >>> world = World()
            >>> world.gravity = (0, -9.81)
            >>> world.gravity
            Vec2(0.0, -9.81)
        """
        g = lib.b2World_GetGravity(self._world_id)
        return Vec2(g.x, g.y)

    @gravity.setter
    def gravity(self, value: VectorLike):
        """Set world gravity vector"""
        value = Vec2(value)
        lib.b2World_SetGravity(self._world_id, value.b2Vec2[0])

    def step(self, time_step, substep_count=4):
        """Advance simulation by time step.

        Args:
            time_step: Time to simulate (seconds)
            substep_count: Number of solver iterations (default 4)
                           Higher values improve stability at cost of performance

        Example:
            >>> world = World()
            >>> world.step(1/60)  # Default 4 substeps
            >>> world.step(0.016, 6)  # Custom substep count
        """
        lib.b2World_Step(self._world_id, time_step, substep_count)

    def new_body(self):
        """Create BodyBuilder for constructing bodies. Entry point for body creation.

        Returns:
            BodyBuilder: Fluent interface for body configuration

        Example:
            >>> world = World()
            >>> builder = world.new_body()
            >>> body = builder.dynamic().position(2,3).circle(1).build()
        """
        return BodyBuilder(self)

    def add_body(
        self,
        body_type: "BodyType | str" = None,
        position: VectorLike = None,
        rotation: float = None,
        linear_velocity: VectorLike = None,
        angular_velocity: float = None,
        linear_damping: float = None,
        angular_damping: float = None,
        gravity_scale: float = None,
        sleep_threshold: float = None,
        name: str = None,
        user_data=None,
        enable_sleep: bool = None,
        is_awake: bool = None,
        lock_x: bool = None,
        lock_y: bool = None,
        lock_rotation: bool = None,
        is_bullet: bool = None,
        is_enabled: bool = None,
        allow_fast_rotation: bool = None,
    ) -> Body:
        """Create a body in this world.

        This is the direct counterpart to :meth:`Body.add_box` and the
        ``add_*_joint`` methods: it makes a body in one call. :meth:`new_body`
        returns a builder for the same thing in fluent style, and builds through
        here.

        Every argument left as None keeps Box2D's default for that property.

        Args:
            body_type: 'static', 'kinematic' or 'dynamic', or a BodyType.
                Defaults to static, as Box2D does.
            position: Initial world position, as a vector-like.
            rotation: Initial world rotation in radians.
            linear_velocity: Initial linear velocity, as a vector-like.
            angular_velocity: Initial angular velocity in radians per second.
            linear_damping: Linear damping, reducing linear velocity. May exceed 1.
            angular_damping: Angular damping, reducing angular velocity. May exceed 1.
            gravity_scale: Scale applied to gravity for this body.
            sleep_threshold: Sleep speed threshold in meters per second.
            name: Optional name for debugging, up to 31 characters.
            user_data: Any Python object to associate with the body. Readable
                afterwards as ``body.user_data``.
            enable_sleep: False if this body should never fall asleep.
            is_awake: Whether the body starts awake.
            lock_x: True to prevent translation along the world x-axis.
            lock_y: True to prevent translation along the world y-axis.
            lock_rotation: True to prevent the body from rotating.
            is_bullet: True to use continuous collision detection for this body.
            is_enabled: False to create the body disabled.
            allow_fast_rotation: True to bypass rotational speed limits.

        Returns:
            Body: The newly created body, with no shapes attached yet. Add them
            with :meth:`Body.add_box`, :meth:`Body.add_circle` and friends.

        Example:
            >>> world = World()
            >>> ground = world.add_body(position=(0, -5))
            >>> _ = ground.add_box(20, 1)
            >>> ball = world.add_body(body_type='dynamic', position=(0, 5))
            >>> _ = ball.add_circle(radius=0.5)
        """
        body_def = BodyDef()

        if body_type is not None:
            body_def.type = Body.resolve_type(body_type)
        if position is not None:
            body_def.position = Vec2(position)
        if rotation is not None:
            body_def.rotation = Rot(rotation)
        if linear_velocity is not None:
            body_def.linear_velocity = Vec2(linear_velocity)
        if angular_velocity is not None:
            body_def.angular_velocity = angular_velocity
        if linear_damping is not None:
            body_def.linear_damping = linear_damping
        if angular_damping is not None:
            body_def.angular_damping = angular_damping
        if gravity_scale is not None:
            body_def.gravity_scale = gravity_scale
        if sleep_threshold is not None:
            body_def.sleep_threshold = sleep_threshold
        if name is not None:
            body_def.name = name
        if user_data is not None:
            body_def.user_data = user_data
        if enable_sleep is not None:
            body_def.enable_sleep = enable_sleep
        if is_awake is not None:
            body_def.is_awake = is_awake
        if lock_x is not None:
            body_def.lock_x = lock_x
        if lock_y is not None:
            body_def.lock_y = lock_y
        if lock_rotation is not None:
            body_def.lock_rotation = lock_rotation
        if is_bullet is not None:
            body_def.is_bullet = is_bullet
        if is_enabled is not None:
            body_def.is_enabled = is_enabled
        if allow_fast_rotation is not None:
            body_def.allow_fast_rotation = allow_fast_rotation

        return Body(self, body_def)

    def add_joint(self, joint_def):
        """Create a joint in this world from a joint definition.

        This is the single place joints are made. The ``add_*_joint`` methods
        below are shorthand that build a definition and call this.

        Args:
            joint_def: Any definition from :mod:`box2d.jointdef`, such as
                :class:`RevoluteJointDef`.

        Returns:
            The created joint.

        Raises:
            ValueError: If either body belongs to a different world, or if a
                definition gives both a world anchor and local anchors.

        Example:
            >>> world = World()
            >>> a = world.add_body(body_type='dynamic', position=(0, 0))
            >>> b = world.add_body(body_type='dynamic', position=(1, 0))
            >>> joint = world.add_joint(
            ...     RevoluteJointDef(a, b, anchor=(0.5, 0), enable_motor=True,
            ...                      max_motor_torque=100)
            ... )
        """
        self._check_bodies(joint_def)
        return joint_def.joint_class(self, **joint_def.joint_arguments())

    def _check_bodies(self, joint_def):
        """Every body a joint connects has to live in this world."""
        bodies = (
            [joint_def.body]
            if isinstance(joint_def, MouseJointDef)
            else [joint_def.body_a, joint_def.body_b]
        )
        for body in bodies:
            if body._body_id not in self._bodies:
                raise ValueError("Every body of a joint must belong to this world")

    def add_mouse_joint(
        self, body, target: VectorLike, max_force=1000.0, damping_ratio=0.7, hertz=5.0
    ) -> "MouseJoint":
        """Drag a body toward a world-space target. See :class:`MouseJointDef`."""
        return self.add_joint(
            MouseJointDef(body, target, max_force, damping_ratio, hertz)
        )

    def add_weld_joint(
        self,
        body_a,
        body_b,
        local_anchor_a: VectorLike = None,
        local_anchor_b: VectorLike = None,
        **kwargs,
    ) -> "WeldJoint":
        """Hold two bodies rigidly together. See :class:`WeldJointDef`."""
        return self.add_joint(
            WeldJointDef(body_a, body_b, local_anchor_a, local_anchor_b, **kwargs)
        )

    def add_revolute_joint(
        self,
        body_a,
        body_b,
        local_anchor_a: VectorLike = None,
        local_anchor_b: VectorLike = None,
        **kwargs,
    ) -> "RevoluteJoint":
        """Pin two bodies at a point they rotate about. See :class:`RevoluteJointDef`."""
        return self.add_joint(
            RevoluteJointDef(body_a, body_b, local_anchor_a, local_anchor_b, **kwargs)
        )

    def add_prismatic_joint(
        self,
        body_a,
        body_b,
        local_anchor_a: VectorLike = None,
        local_anchor_b: VectorLike = None,
        **kwargs,
    ) -> "PrismaticJoint":
        """Let two bodies slide along one axis. See :class:`PrismaticJointDef`."""
        return self.add_joint(
            PrismaticJointDef(body_a, body_b, local_anchor_a, local_anchor_b, **kwargs)
        )

    def add_wheel_joint(
        self,
        body_a,
        body_b,
        local_anchor_a: VectorLike = None,
        local_anchor_b: VectorLike = None,
        **kwargs,
    ) -> "WheelJoint":
        """A sliding axis with a spring, as for suspension. See :class:`WheelJointDef`."""
        return self.add_joint(
            WheelJointDef(body_a, body_b, local_anchor_a, local_anchor_b, **kwargs)
        )

    def add_distance_joint(
        self,
        body_a,
        body_b,
        local_anchor_a: VectorLike = None,
        local_anchor_b: VectorLike = None,
        **kwargs,
    ) -> "DistanceJoint":
        """Keep two points a fixed distance apart. See :class:`DistanceJointDef`."""
        return self.add_joint(
            DistanceJointDef(body_a, body_b, local_anchor_a, local_anchor_b, **kwargs)
        )

    def add_motor_joint(self, body_a, body_b, **kwargs) -> "MotorJoint":
        """Drive the relative motion of two bodies. See :class:`MotorJointDef`."""
        return self.add_joint(MotorJointDef(body_a, body_b, **kwargs))

    def _track_body(self, body: "Body"):
        """Internal method to track body references. Called automatically during body creation.

        Args:
            body: Body instance to register in the world
        """
        self._bodies[body._body_id] = body

    @property
    def bodies(self):
        """Get list of all active bodies in the world.

        Returns:
            list[Body]: Copies of registered body references

        Example:
            >>> world = World()
            >>> box = world.new_body().dynamic().build()
            >>> len(world.bodies)
            1
        """
        return list(self._bodies.values())

    def explode(
        self,
        position: VectorLike,
        radius: float,
        impulse_per_length: float,
        falloff: float = None,
        mask: int = None,
    ) -> None:
        """Apply a radial impulse to everything within a radius.

        Box2D pushes each dynamic shape whose surface falls inside the circle,
        scaled by how much of it is exposed, so a wide body is thrown harder
        than a narrow one at the same distance.

        Args:
            position: Centre of the explosion, in world coordinates.
            radius: How far the blast reaches, in metres.
            impulse_per_length: Impulse applied per metre of exposed surface.
                Negative values pull inward, making an implosion.
            falloff: Distance over which the impulse fades to nothing past the
                radius. Defaults to Box2D's own value.
            mask: Collision mask deciding which shapes are affected. Defaults
                to everything.

        Example:
            >>> world = World()
            >>> body = world.add_body(body_type='dynamic', position=(1, 0))
            >>> _ = body.add_circle(radius=0.5)
            >>> world.explode((0, 0), radius=5.0, impulse_per_length=10.0)
            >>> world.step(1 / 60, 4)
        """
        explosion = lib.b2DefaultExplosionDef()
        explosion.position = Vec2(position).b2Vec2[0]
        explosion.radius = float(radius)
        explosion.impulsePerLength = float(impulse_per_length)
        if falloff is not None:
            explosion.falloff = float(falloff)
        if mask is not None:
            explosion.maskBits = int(mask)
        lib.b2World_Explode(self._world_id, ffi.addressof(explosion))

    def draw(self, debug_draw: DebugDraw):
        """Render world state using debug drawing interface.

        Args:
            debug_draw: Configured DebugDraw instance for visualization

        Example:
            >>> world = World()
            >>> debug_draw = DebugDraw()
            >>> world.draw(debug_draw)
        """
        lib.b2World_Draw(self._world_id, ffi.addressof(debug_draw._debug_draw))

    def query_aabb(
        self,
        aabb: AABB,
        filter: "CollisionFilter" = None,
        max_results: int = None,
    ) -> list:
        """Find shapes overlapping an axis-aligned bounding box using an optional collision filter.

        Args:
            aabb: Axis-aligned bounding box to query.
            filter: Optional CollisionFilter instance for filtering.
                If None, a default CollisionFilter is used.
            max_results: Optional maximum number of shapes to return.

        Returns:
            list: Shapes with overlapping fixtures.

        Example:
            >>> world = World()
            >>> box = world.new_body().dynamic().position(0, 0).box(1, 1).build()
            >>> aabb = AABB(lower=Vec2(-1, -1), upper=Vec2(1, 1))
            >>> overlaps = world.query_aabb(aabb, filter=CollisionFilter(), max_results=10)
            >>> len(overlaps) <= 10
            True
        """

        if filter is None:
            filter = CollisionFilter()

        results = []
        overlap_callback = make_overlap_callback(results, max_results)

        # Convert the CollisionFilter to a Box2D c_filter.
        c_filter = filter.b2QueryFilter
        filter_dict = {
            "categoryBits": c_filter.categoryBits,
            "maskBits": c_filter.maskBits,
        }

        # 3.2 added a query origin for large-world support. Coordinates in
        # this binding are absolute, so the origin is always the world origin.
        lib.b2World_OverlapAABB(
            self._world_id,
            Vec2(0, 0).b2Vec2[0],
            aabb.b2AABB[0],
            c_filter[0],
            overlap_callback,
            ffi.NULL,
        )
        return results

    def query_circle(
        self,
        position: VectorLike,
        radius: float,
        filter: "CollisionFilter" = None,
        max_results: int = None,
    ) -> list:
        """Find shapes overlapping a circle.

        Args:
            position: Center of the query circle in world coordinates.
            radius: Radius of the query circle.
            collision_filter: Optional CollisionFilter instance for filtering.
                              If None, a default CollisionFilter is used.
            max_results: Optional maximum number of shapes to return.
                         The callback will return False when this limit is reached.

        Returns:
            list: Shapes with overlapping fixtures.

        Example:
            >>> world = World()
            >>> # Create a body with a circle fixture
            >>> box = world.new_body().dynamic().circle(1).build()
            >>> overlaps = world.query_circle((0, 0), 1.5, filter=CollisionFilter(), max_results=10)
            >>> len(overlaps) <= 10
            True
        """
        if filter is None:
            filter = CollisionFilter()

        results = []
        overlap_callback = make_overlap_callback(results, max_results)

        # Box2D 3.1 replaced b2World_OverlapCircle with the general
        # b2World_OverlapShape. A circle is a single-point proxy with a radius.
        proxy = ffi.new("b2ShapeProxy*")
        proxy.points[0] = Vec2(position).b2Vec2[0]
        proxy.count = 1
        proxy.radius = radius
        c_filter = filter.b2QueryFilter

        # 3.2 added a query origin for large-world support. Coordinates in
        # this binding are absolute, so the origin is always the world origin.
        lib.b2World_OverlapShape(
            self._world_id,
            Vec2(0, 0).b2Vec2[0],
            proxy,
            c_filter[0],
            overlap_callback,
            ffi.NULL,
        )
        return results

    def ray_cast(
        self,
        origin: VectorLike,
        translation: VectorLike,
        filter: "CollisionFilter" = None,
        first_hit_only: bool = False,
    ) -> list[RayCastResult]:
        """Cast a ray and find intersecting shapes.

        Args:
            origin: Starting point of the ray (x,y)
            translation: The translation of the ray from the start point to the end point
            filter: Optional filter to control which shapes are tested
            first_hit_only: If True, only return the first hit encountered

        Returns:
            List of RayCastResult objects containing hit information

        Example:
            >>> world = World()
            >>> box = world.new_body().dynamic().position(5,0).box(1,1).build()
            >>> hits = world.ray_cast((0,0), (10,0))
            >>> len(hits) > 0
            True
            >>> s = hits[0].shape  # First intersected shape
            >>> isinstance(s, Shape)
            True
        """
        if filter is None:
            filter = CollisionFilter()

        results = []

        p1 = Vec2(origin).b2Vec2[0]
        p2 = Vec2(translation).b2Vec2[0]
        c_filter = filter.b2QueryFilter
        if first_hit_only:
            result = lib.b2World_CastRayClosest(self._world_id, p1, p2, c_filter[0])
            if result.hit:
                results.append(
                    RayCastResult(
                        shape=ffi.from_handle(lib.b2Shape_GetUserData(result.shapeId)),
                        point=Vec2(result.point.x, result.point.y),
                        normal=Vec2(result.normal.x, result.normal.y),
                        fraction=result.fraction,
                    )
                )
        else:
            callback = make_ray_cast_callback(results)
            lib.b2World_CastRay(self._world_id, p1, p2, c_filter[0], callback, ffi.NULL)
        results.sort(key=lambda r: r.fraction)
        return results

    def get_sensor_events(self) -> list:
        """Retrieve all sensor events that occurred during the last time step.

        Sensors are shapes marked with is_sensor=True. They detect overlap with
        other shapes but don't generate collision responses. This method returns
        all begin and end overlap events for sensors from the last simulation step.

        Returns:
            list: A list of SensorEvent objects with the following attributes:
                - sensor: The sensor Shape that detected overlap
                - visitor: The Shape that overlapped with the sensor
                - begin: True if overlap began, False if overlap ended

        Example:
            >>> world = World()
            >>> body = world.new_body().dynamic().position(0,0).build()
            >>> # Create a sensor fixture
            >>> sensor = body.add_circle(radius=1.0, is_sensor=True)
            >>> # Run simulation
            >>> world.step(1/60)
            >>> # Get events
            >>> events = world.get_sensor_events()
            >>> for event in events.begin:
            ...      print(f"Sensor began contact with object")

        """
        events = []

        # Get the events from Box2D
        sensor_events = lib.b2World_GetSensorEvents(self._world_id)

        # Process the events if there are any
        if sensor_events:
            # Determine how many events we have
            begin_count = sensor_events.beginCount
            end_count = sensor_events.endCount

            # Process each event
            begin_ev = [sensor_events.beginEvents[i] for i in range(begin_count)]
            end_ev = [sensor_events.endEvents[i] for i in range(end_count)]
            begin_events = [
                SensorEvent(
                    sensor=ffi.from_handle(
                        lib.b2Shape_GetUserData(event.sensorShapeId)
                    ),
                    visitor=ffi.from_handle(
                        lib.b2Shape_GetUserData(event.visitorShapeId)
                    ),
                    begin=True,
                )
                for event in begin_ev
            ]
            end_events = [
                SensorEvent(
                    sensor=ffi.from_handle(
                        lib.b2Shape_GetUserData(event.sensorShapeId)
                    ),
                    visitor=ffi.from_handle(
                        lib.b2Shape_GetUserData(event.visitorShapeId)
                    ),
                    begin=False,
                )
                for event in end_ev
            ]

        return SensorEvents(begin=begin_events, end=end_events)

    @staticmethod
    def _shape_from_id(shape_id):
        """Resolve a shape id back to its wrapper, or None if it is gone.

        End-touch events can name a shape that was destroyed during the step,
        so this has to tolerate that rather than hand back a dangling wrapper.
        """
        if not lib.b2Shape_IsValid(shape_id):
            return None
        data = lib.b2Shape_GetUserData(shape_id)
        return ffi.from_handle(data) if data != ffi.NULL else None

    # --- callbacks Box2D invokes during a step ------------------------------
    #
    # Each one keeps both the user's function and the cffi trampoline wrapping
    # it on the World. Dropping the trampoline would let it be collected while
    # Box2D still holds the pointer, which crashes on the next step.
    #
    # None of these may touch the world: Box2D calls them mid-solve, and
    # creating or destroying anything from inside one corrupts the step.

    @property
    def custom_filter(self):
        """Get or set a callback deciding whether two shapes may collide.

        Called as ``fn(shape_a, shape_b)`` returning False to cancel the
        contact. Consulted only when at least one of the shapes was created
        with ``enable_custom_filtering=True``, so it is cheap to leave set.

        Assign None to remove it. Use this for rules that categories and masks
        cannot express, such as "these two specific bodies never collide".

        Example:
            >>> world = World()
            >>> world.custom_filter = lambda a, b: a.body is not b.body
        """
        return self._custom_filter

    @custom_filter.setter
    def custom_filter(self, function):
        if function is None:
            lib.b2World_SetCustomFilterCallback(self._world_id, ffi.NULL, ffi.NULL)
            self._custom_filter = self._custom_filter_trampoline = None
            return

        resolve = self._shape_from_id

        # Exceptions are caught here rather than left to cffi's error= path,
        # which reports them as unraisable. Allowing the collision is the
        # harmless answer when the callback cannot decide.
        @ffi.callback("bool(b2ShapeId, b2ShapeId, void*)")
        def trampoline(shape_id_a, shape_id_b, _context):
            try:
                return bool(function(resolve(shape_id_a), resolve(shape_id_b)))
            except Exception:
                traceback.print_exc()
                return True

        self._custom_filter = function
        self._custom_filter_trampoline = trampoline
        lib.b2World_SetCustomFilterCallback(self._world_id, trampoline, ffi.NULL)

    @property
    def pre_solve(self):
        """Get or set a callback run just before each contact is solved.

        Called as ``fn(shape_a, shape_b, point, normal)`` returning False to
        disable that contact for this step. Only for shapes created with
        ``enable_pre_solve_events=True``, and never for sensors.

        Assign None to remove it. This is how one-way platforms are built: let
        a body through when it is moving upward, block it otherwise.

        Note:
            Box2D may call this from worker threads when the world has more
            than one, so the callback must not touch shared state unguarded.
        """
        return self._pre_solve

    @pre_solve.setter
    def pre_solve(self, function):
        if function is None:
            lib.b2World_SetPreSolveCallback(self._world_id, ffi.NULL, ffi.NULL)
            self._pre_solve = self._pre_solve_trampoline = None
            return

        resolve = self._shape_from_id

        # As above: a callback that raises keeps the contact rather than
        # silently dropping it, which would look like objects falling through.
        @ffi.callback("bool(b2ShapeId, b2ShapeId, b2Vec2, b2Vec2, void*)")
        def trampoline(shape_id_a, shape_id_b, point, normal, _context):
            try:
                return bool(
                    function(
                        resolve(shape_id_a),
                        resolve(shape_id_b),
                        Vec2(point.x, point.y),
                        Vec2(normal.x, normal.y),
                    )
                )
            except Exception:
                traceback.print_exc()
                return True

        self._pre_solve = function
        self._pre_solve_trampoline = trampoline
        lib.b2World_SetPreSolveCallback(self._world_id, trampoline, ffi.NULL)

    @property
    def friction_mixer(self):
        """Get or set how two shapes' frictions combine into a contact friction.

        Called as ``fn(friction_a, material_a, friction_b, material_b)``
        returning the friction to use. The material arguments are the shapes'
        user material ids, which is what makes rules like "rubber on ice"
        possible. Assign None to restore Box2D's default, the geometric mean.

        Note:
            Box2D calls this from worker threads and gives it no context, so it
            must not touch Box2D or application state. If it raises, the
            default mixing is used for that contact.
        """
        return self._friction_mixer

    @friction_mixer.setter
    def friction_mixer(self, function):
        if function is None:
            lib.b2World_SetFrictionCallback(self._world_id, ffi.NULL)
            self._friction_mixer = self._friction_trampoline = None
            return

        @ffi.callback("float(float, uint64_t, float, uint64_t)")
        def trampoline(friction_a, material_a, friction_b, material_b):
            try:
                return float(function(friction_a, material_a, friction_b, material_b))
            except Exception:
                traceback.print_exc()
                return math.sqrt(friction_a * friction_b)

        self._friction_mixer = function
        self._friction_trampoline = trampoline
        lib.b2World_SetFrictionCallback(self._world_id, trampoline)

    @property
    def restitution_mixer(self):
        """Get or set how two shapes' restitutions combine.

        Called as ``fn(restitution_a, material_a, restitution_b, material_b)``
        returning the restitution to use. Assign None to restore Box2D's
        default, the larger of the two.

        Note:
            The same worker-thread restriction as :attr:`friction_mixer`. If it
            raises, the default mixing is used for that contact.
        """
        return self._restitution_mixer

    @restitution_mixer.setter
    def restitution_mixer(self, function):
        if function is None:
            lib.b2World_SetRestitutionCallback(self._world_id, ffi.NULL)
            self._restitution_mixer = self._restitution_trampoline = None
            return

        @ffi.callback("float(float, uint64_t, float, uint64_t)")
        def trampoline(restitution_a, material_a, restitution_b, material_b):
            try:
                return float(
                    function(restitution_a, material_a, restitution_b, material_b)
                )
            except Exception:
                traceback.print_exc()
                return max(restitution_a, restitution_b)

        self._restitution_mixer = function
        self._restitution_trampoline = trampoline
        lib.b2World_SetRestitutionCallback(self._world_id, trampoline)

    def get_contact_events(self) -> ContactEvents:
        """Contacts that began, ended, or hit during the last step.

        Contacts are only reported for shapes that opted in. Begin and end need
        ``enable_contact_events`` on both shapes; hits need ``enable_hit_events``
        and an approach speed above :attr:`hit_event_threshold`. Box2D defaults
        all of these off.

        Returns:
            ContactEvents: with ``begin``, ``end`` and ``hit`` lists, describing
            only the step that just finished. Reading does not consume them, so
            asking twice between steps gives the same answer; the next step
            replaces them.

        Example:
            >>> world = World()
            >>> body = world.add_body(body_type='dynamic', position=(0, 5))
            >>> _ = body.add_circle(radius=0.5, enable_contact_events=True)
            >>> ground = world.add_body(position=(0, 0))
            >>> _ = ground.add_box(20, 1, enable_contact_events=True)
            >>> for _ in range(200):
            ...     world.step(1 / 60, 4)
            ...     for touch in world.get_contact_events().begin:
            ...         pass  # touch.shape_a and touch.shape_b just met
        """
        events = lib.b2World_GetContactEvents(self._world_id)
        resolve = self._shape_from_id

        begin = [
            ContactBeginEvent(
                shape_a=resolve(event.shapeIdA),
                shape_b=resolve(event.shapeIdB),
                contact=Contact(event.contactId),
            )
            for event in (events.beginEvents[i] for i in range(events.beginCount))
        ]
        end = [
            ContactEndEvent(
                shape_a=resolve(event.shapeIdA),
                shape_b=resolve(event.shapeIdB),
                contact=Contact(event.contactId),
            )
            for event in (events.endEvents[i] for i in range(events.endCount))
        ]
        hit = [
            ContactHitEvent(
                shape_a=resolve(event.shapeIdA),
                shape_b=resolve(event.shapeIdB),
                point=Vec2(event.point.x, event.point.y),
                normal=Vec2(event.normal.x, event.normal.y),
                approach_speed=event.approachSpeed,
                contact=Contact(event.contactId),
            )
            for event in (events.hitEvents[i] for i in range(events.hitCount))
        ]
        return ContactEvents(begin=begin, end=end, hit=hit)

    def get_body_events(self) -> list:
        """Bodies that moved during the last step.

        Box2D reports only bodies that actually moved, so this is cheaper than
        walking every body to refresh what you draw.

        Returns:
            list[BodyMoveEvent]: One per body that moved.
        """
        events = lib.b2World_GetBodyEvents(self._world_id)
        moves = []
        for i in range(events.moveCount):
            event = events.moveEvents[i]
            if event.userData == ffi.NULL:
                continue
            moves.append(
                BodyMoveEvent(
                    body=ffi.from_handle(event.userData),
                    transform=Transform.from_b2Transform(event.transform),
                    fell_asleep=bool(event.fellAsleep),
                )
            )
        return moves

    def get_joint_events(self) -> list:
        """Joints that passed their force or torque threshold last step.

        A joint reports nothing unless its definition set ``force_threshold`` or
        ``torque_threshold``, so this is how a breakable construction learns
        which of its joints is about to give.

        Returns:
            list[JointEvent]: One per joint that reported.
        """
        events = lib.b2World_GetJointEvents(self._world_id)
        reports = []
        for i in range(events.count):
            event = events.jointEvents[i]
            if event.userData == ffi.NULL:
                continue
            reports.append(JointEvent(joint=ffi.from_handle(event.userData)))
        return reports

    @property
    def is_valid(self) -> bool:
        """Whether this world is still live, i.e. has not been destroyed."""
        return is_live(self, "_world_id", lib.b2World_IsValid)

    def destroy(self):
        """Destroy the world.

        Destroying a world also destroys every body, shape and joint in it.
        Those objects raise :class:`DestroyedError` if used afterwards.

        Example:
            >>> world = World()
            >>> world.destroy()
        """
        # If using the C-level scheduler, clean it up.
        if getattr(self, "_use_c_scheduler", False):
            lib.cleanup_threadpool()
            self._use_c_scheduler = False

        # Read past the validity check: destroy must stay callable (and a no-op)
        # on an already-destroyed world, since __del__ routes through here.
        raw = raw_id(self, "_world_id")
        if raw is not None:
            if lib.b2World_IsValid(raw):
                lib.b2DestroyWorld(raw)
            del self._world_id

    def __del__(self):
        """Clean up world resources. Automatically called when instance is garbage collected.

        Destroys Box2D world instance.
        """
        self.destroy()

    @property
    def enable_sleep(self) -> bool:
        """Control whether bodies can enter sleep state to save computation.

        When enabled, inactive bodies will stop simulating until awakened.

        Example:
            >>> world = World()
            >>> world.enable_sleep = False  # Disable sleeping entirely
        """
        return self._enable_sleep

    @enable_sleep.setter
    def enable_sleep(self, value: bool):
        self._enable_sleep = bool(value)
        lib.b2World_EnableSleeping(self._world_id, self._enable_sleep)

    @property
    def enable_continuous(self) -> bool:
        """Toggle continuous collision detection for dynamic vs static bodies.

        Helps prevent fast-moving objects from tunneling through static geometry.

        Example:
            >>> world = World()
            >>> world.enable_continuous = False  # Disable CCD for static
        """
        return self._enable_continuous

    @enable_continuous.setter
    def enable_continuous(self, value: bool):
        self._enable_continuous = bool(value)
        lib.b2World_EnableContinuous(self._world_id, self._enable_continuous)

    @property
    def restitution_threshold(self) -> float:
        """Minimum collision speed for restitution effects (m/s).

        Collisions slower than this threshold will have zero restitution.

        Example:
            >>> world = World()
            >>> world.restitution_threshold = 2.0  # Only apply restitution above 2m/s
        """
        return self._restitution_threshold

    @restitution_threshold.setter
    def restitution_threshold(self, value: float):
        self._restitution_threshold = float(value)
        lib.b2World_SetRestitutionThreshold(self._world_id, self._restitution_threshold)

    @property
    def hit_event_threshold(self) -> float:
        """Minimum collision speed to trigger hit events (m/s).

        Collisions slower than this won't generate collision events.

        Example:
            >>> world = World()
            >>> world.hit_event_threshold = 0.5  # Get events for slower impacts
        """
        return self._hit_event_threshold

    @hit_event_threshold.setter
    def hit_event_threshold(self, value: float):
        self._hit_event_threshold = float(value)
        lib.b2World_SetHitEventThreshold(self._world_id, self._hit_event_threshold)

    @property
    def contact_hertz(self) -> float:
        """Contact constraint stiffness frequency (Hz).

        Higher values make contacts stiffer/more rigid.

        Example:
            >>> world = World()
            >>> world.contact_hertz = 30.0  # Softer contacts
        """
        return self._contact_hertz

    @contact_hertz.setter
    def contact_hertz(self, value: float):
        self._contact_hertz = float(value)
        lib.b2World_SetContactTuning(
            self._world_id,
            self._contact_hertz,
            self._contact_damping_ratio,
            self._contact_push_velocity,
        )

    @property
    def contact_damping_ratio(self) -> float:
        """Contact constraint damping ratio (0-1).

        1.0 = critical damping (fastest oscillation reduction)

        Example:
            >>> world = World()
            >>> world.contact_damping_ratio = 0.2  # Add some energy absorption
        """
        return self._contact_damping_ratio

    @contact_damping_ratio.setter
    def contact_damping_ratio(self, value: float):
        self._contact_damping_ratio = float(value)
        lib.b2World_SetContactTuning(
            self._world_id,
            self._contact_hertz,
            self._contact_damping_ratio,
            self._contact_push_velocity,
        )

    @property
    def contact_push_velocity(self) -> float:
        """Maximum velocity for pushing objects out of penetration (m/s).

        Limits how fast contacts can separate penetrating bodies.

        Example:
            >>> world = World()
            >>> world.contact_push_velocity = 2.0  # Allow faster separation
        """
        return self._contact_push_velocity

    @contact_push_velocity.setter
    def contact_push_velocity(self, value: float):
        self._contact_push_velocity = float(value)
        lib.b2World_SetContactTuning(
            self._world_id,
            self._contact_hertz,
            self._contact_damping_ratio,
            self._contact_push_velocity,
        )
