[build-system]
requires = ["setuptools>=75.8.0", "cffi>=1.16.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "box2d-py"
version = "0.1.1"
description = "Bindings for box2d v3"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
  { name = "Giorgos Giagas", email = "giorgosg@gmail.com" }
]
maintainers = [
  { name = "Giorgos Giagas", email = "giorgosg@gmail.com" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "cffi>=1.16.0"
]

[project.optional-dependencies]
testbed = [
  "imgui_bundle",
  "PyOpenGL",
  "PyOpenGL-accelerate",
  "numpy"
]

[project.scripts]
box2d-testbed = "box2d_testbed:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["box2d*", "box2d_testbed*"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.rst", "*.so", "*.pyd", "*.dll", "*.vs", "*.fs"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
  "src/tests",
]